# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo {{.locustMaster}}
    silent: true

  apply:
    cmds:
    - ansible-playbook -i inventory main.yml -v 